spring.application.name=techtalks_skill_based_recruitment
server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/skill_based_recruitment_db
spring.datasource.username=root
spring.datasource.password=Ss100200
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
