spring.application.name=techtalks_skill_based_recruitment
server.port=8082

spring.datasource.url=jdbc:mysql://127.0.0.1:3307/skill_based_recruitment_db
spring.datasource.username=springuser
spring.datasource.password=springpass
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=8f3c1a9e6b2d4f7a0c5e8b1d4f7a0c3e6b9d2f5a8c1e4b7d0a3f6c9e2b5d8f1a
jwt.expiration-ms=86400000